// flow-typed signature: 2e3f81167b92a9104e7cef3e06545e72
// flow-typed version: <<STUB>>/restify-router_v^0.4.2/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'restify-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'restify-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'restify-router/lib/router' {
  declare module.exports: any;
}

// Filename aliases
declare module 'restify-router/index' {
  declare module.exports: $Exports<'restify-router'>;
}
declare module 'restify-router/index.js' {
  declare module.exports: $Exports<'restify-router'>;
}
declare module 'restify-router/lib/router.js' {
  declare module.exports: $Exports<'restify-router/lib/router'>;
}
