swagger: "2.0"
info:
  version: "0.0.1"
  title: Restify boilerplate
host: localhost:8080
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  $ref: src/api/swagger/paths/index.yaml
definitions:
  $ref: src/api/swagger/definations/index.yaml
